# Generated by Django 5.0.5 on 2024-05-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='e_image',
            field=models.ImageField(default='1', upload_to='images'),
        ),
    ]
