# Generated by Django 5.0.5 on 2024-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_event_e_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_category', models.CharField(max_length=50)),
                ('e_desc', models.CharField(max_length=300)),
                ('e_date', models.DateField()),
                ('e_image', models.ImageField(default='1', upload_to='images')),
                ('e_price', models.FloatField(default=0)),
                ('e_state', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='e_price',
            field=models.FloatField(default=0),
        ),
    ]
