# Generated by Django 5.0.5 on 2024-05-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_alter_eventfull_e_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfull',
            name='e_state',
            field=models.IntegerField(choices=[(1, 'Maharashtra'), (2, 'Sikkim'), (3, 'Uttarakhand'), (4, 'Karnataka'), (5, 'Himachal Pradesh')], verbose_name='state'),
        ),
    ]
