# Generated by Django 5.0.5 on 2024-05-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_eventdetails_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfull',
            name='e_itinerary',
            field=models.TextField(default='abc'),
        ),
    ]
