# Generated by Django 5.0.5 on 2024-05-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_enroll_delete_eventdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='qty',
            new_name='n_participants',
        ),
    ]
