# Generated by Django 5.0.5 on 2024-05-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_rename_qty_enroll_n_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='c_name',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='c_phone',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='n_participants',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='pid',
        ),
        migrations.AddField(
            model_name='enroll',
            name='eid',
            field=models.ForeignKey(db_column='e_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='travelapp.eventfull'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParticipantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_mobile', models.BigIntegerField()),
                ('no_participants', models.IntegerField()),
                ('userid', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
