# Generated by Django 5.0.5 on 2024-05-18 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0016_remove_enroll_no_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_participants', models.IntegerField(default=1)),
                ('eid', models.ForeignKey(db_column='e_id', on_delete=django.db.models.deletion.CASCADE, to='travelapp.eventfull')),
                ('userid', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
