# Generated by Django 5.0.5 on 2024-05-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0017_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='n_participants',
        ),
        migrations.AddField(
            model_name='confirm',
            name='participants',
            field=models.ForeignKey(db_column='nparticipants', default=1, on_delete=django.db.models.deletion.CASCADE, to='travelapp.enroll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enroll',
            name='no_participants',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
