# Generated by Django 5.0.5 on 2024-05-20 05:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0018_remove_confirm_n_participants_confirm_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enqiury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
    ]
