# Generated by Django 5.0.5 on 2024-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0019_enqiury'),
    ]

    operations = [
        migrations.AddField(
            model_name='enqiury',
            name='emial',
            field=models.EmailField(default='a@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
