# Generated by Django 5.0.5 on 2024-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0020_enqiury_emial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm',
            name='participants',
            field=models.IntegerField(default=1),
        ),
    ]
